services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jekyll_app
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development